Repository getnikola/nikola, pull requests merged in 2018-09, with the labels that each got.

#3151 Fix #3074 — get rid of the webassets library
  CHANGES.txt
  docs/creating-a-theme.rst
  docs/manual.rst
  docs/theming.rst
  nikola/conf.py.in
  nikola/plugins/task/bundles.plugin
  nikola/plugins/task/bundles.py
  requirements-extras.txt
  snapcraft.yaml
Labels: enhancement, infrastructure, minor

#3146 Fix #3140 — enforce trailing slash for directories in auto
  CHANGES.txt
  nikola/plugins/command/auto/__init__.py
Labels: bug, minor

#3152 Fix #3141 — stop calling baguetteBox.run twice
  CHANGES.txt
  nikola/data/themes/base/assets/js/gallery.js
  nikola/data/themes/base/assets/js/gallery.min.js
  nikola/data/themes/bootblog4-jinja/templates/base.tmpl
  nikola/data/themes/bootblog4/templates/base.tmpl
Labels: bug

#3156 Fix #2863 — allow light navbar in bootstrap4
  CHANGES.txt
  nikola/conf.py.in
  nikola/data/themes/bootstrap4-jinja/templates/base.tmpl
  nikola/data/themes/bootstrap4/templates/base.tmpl
Labels: enhancement, visual

#3158 Remove doctitle if not using reST docinfo metadata
  CHANGES.txt
  nikola/conf.py.in
  nikola/plugins/compile/rest/__init__.py
Labels: breaks backwards compatibility, enhancement, user experience

#3161 Move tagcloud plugin to repo
  CHANGES.txt
  docs/manual.rst
  nikola/conf.py.in
  nikola/nikola.py
  nikola/plugins/task/tagcloud.plugin
  nikola/plugins/task/tagcloud.py
Labels: minor

#3162 Added Malayalam translation by nemo@dicto.xyz
  translations/nikola.messages/ml.po
Labels: i18n

#3168 Fix #3167 — fix docinfo removal for sites that use reST docinfo
  CHANGES.txt
  docs/creating-a-site.rst
  docs/creating-a-theme.rst
  docs/extending.rst
  docs/internals.rst
  docs/manual.rst
  docs/social_buttons.rst
  docs/theming.rst
  nikola/data/samplesite/pages/quickstart.rst
  nikola/nikola.py
  nikola/plugins/compile/rest/__init__.py
Labels: bug

#3169 Set reST logging level to WARNING to limit noise
  CHANGES.txt
  nikola/plugins/compile/rest/__init__.py
Labels: minor, user experience
