Repository getnikola/nikola, pull requests merged in 2018-05, with the labels that each got.

#3066 [WIP] Change draft, private and mathjax to own metadata (#2761)
  CHANGES.txt
  docs/manual.rst
  nikola/conf.py.in
  nikola/data/themes/base-jinja/templates/math_helper.tmpl
  nikola/data/themes/base/templates/math_helper.tmpl
  nikola/nikola.py
  nikola/plugins/command/import_wordpress.py
  nikola/post.py
  scripts/jinjify.py
Labels: in progress

#3068 [WIP] Conversion plugin for #2761
  nikola/post.py
Labels: in progress

#3067 Use one file for Atom feeds
  CHANGES.txt
  nikola/conf.py.in
  nikola/nikola.py
  nikola/plugin_categories.py
  nikola/plugins/misc/taxonomies_classifier.py
  nikola/plugins/task/archive.py
  nikola/plugins/task/authors.py
  nikola/plugins/task/categories.py
  nikola/plugins/task/indexes.py
  nikola/plugins/task/page_index.py
  nikola/plugins/task/sections.py
  nikola/plugins/task/tags.py
  nikola/plugins/task/taxonomies.py
Labels: enhancement

#3065 Drop useless settings
  CHANGES.txt
  docs/template-variables.rst
  nikola/conf.py.in
  nikola/data/themes/base-jinja/templates/base_helper.tmpl
  nikola/data/themes/base-jinja/templates/post_helper.tmpl
  nikola/data/themes/base/templates/base_helper.tmpl
  nikola/data/themes/base/templates/post_helper.tmpl
  nikola/data/themes/bootblog4-jinja/templates/base_helper.tmpl
  nikola/data/themes/bootblog4/templates/base_helper.tmpl
  nikola/data/themes/bootstrap4-jinja/templates/base_helper.tmpl
  nikola/data/themes/bootstrap4/templates/base_helper.tmpl
  nikola/nikola.py
  nikola/plugins/task/sitemap/__init__.py
Labels: breaks backwards compatibility

#3064 Arbitrary metadata for galleries (#3050)
  CHANGES.txt
  docs/manual.rst
  nikola/data/samplesite/galleries/demo/metadata.yml
  nikola/plugins/task/galleries.py
Labels: enhancement, feature request

#3071 Merge categories and sections (nuke sections)
  CHANGES.txt
  docs/manual.rst
  docs/template-variables.rst
  nikola/conf.py.in
  nikola/data/themes/base-jinja/templates/sectionindex.tmpl
  nikola/data/themes/base/templates/sectionindex.tmpl
  nikola/nikola.py
  nikola/plugins/task/categories.py
  nikola/plugins/task/sections.plugin
  nikola/plugins/task/sections.py
  nikola/plugins/task/tags.py
  nikola/post.py
  nikola/utils.py
Labels: enhancement

#3085 Support CATEGORY_DESTPATH_NAMES with pages following destpath
  CHANGES.txt
  nikola/conf.py.in
  nikola/plugins/task/categories.py
Labels: bug

#3088 Add NAVIGATION_ALT_LINKS
  CHANGES.txt
  docs/creating-a-theme.rst
  docs/manual.rst
  docs/template-variables.rst
  nikola/conf.py.in
  nikola/data/themes/base-jinja/templates/base_header.tmpl
  nikola/data/themes/base/templates/base_header.tmpl
  nikola/data/themes/bootblog4-jinja/templates/base.tmpl
  nikola/data/themes/bootblog4-jinja/templates/base_helper.tmpl
  nikola/data/themes/bootblog4-jinja/templates/ui_helper.tmpl
  nikola/data/themes/bootblog4/assets/css/bootblog.css
  nikola/data/themes/bootblog4/templates/base.tmpl
  nikola/data/themes/bootblog4/templates/base_helper.tmpl
  nikola/data/themes/bootblog4/templates/ui_helper.tmpl
  nikola/data/themes/bootstrap4-jinja/templates/base.tmpl
  nikola/data/themes/bootstrap4-jinja/templates/base_helper.tmpl
  nikola/data/themes/bootstrap4/templates/base.tmpl
  nikola/data/themes/bootstrap4/templates/base_helper.tmpl
  nikola/nikola.py
Labels: feature request
